### ISSUE TITLE
Fiddler Root Certificate NOT trusted successfully

### ISSUE THREAD

**Issue by sanghavan** [telerik/fiddler-everywhere-docs#105]
**OS**: Mac OS Big Sur 11.0.1
**Fiddler Everywhere version**: 1.2.1

I already followed the article https://docs.telerik.com/fiddler-everywhere/knowledge-base/how-to-install-fiddler-root-certificate-on-mac-os, but it still got fail "Fiddler Root Certificate NOT trusted successfully". I checked the cert in keychain, it's trusted.

**Comment by NickIliev** [comment]
Hello @sanghavan ,


First of all, accept our apologies for the delay in our response!

Could you please verify that the issue persists with the latest version of Fiddler Everywhere? If so, then please try to remove any existing Fiddler certificates from your keychain and then follow the procedure steps for adding certificate manually (as shown in [the linked article](https://docs.telerik.com/fiddler-everywhere/knowledge-base/how-to-install-fiddler-root-certificate-on-mac-os#installing-the-certificate-manually)).

If you are still experiencing the issue, you could access and provide the Fiddler Everywhere logs (refer[ to this KB ](https://docs.telerik.com/fiddler-everywhere/knowledge-base/accessing-fiddler-logs)for instructions on how to access the FE log files)

As a side note, you could also check[ the Fiddler Everywhere forums](https://community.getfiddler.com/support/discussions/forums/12000000870) for similar issues and possible solutions discussed by the team members and other community members.

**Comment by ivanpadavan** [comment]
Hello @NickIliev! Can I get the previous version (1.5.1 as for comment date) of Fiddler Everywhere? I'm getting an exception 
`fiddler.network.https> HTTPS handshake to sdp5-dev-sdp01 (for #1500) failed. System.IO.IOException Cannot determine the frame size or a corrupted frame was received.`
while trying to proxy from expired certificate
I think it's due to .NET 5.0 update, may be there is some way to get specific version from the [API](https://api.getfiddler.com/index.html?)
