### ISSUE TITLE
Deleting fiddler certificate

### ISSUE THREAD

**Issue by hiddenscroll** [telerik/fiddler-everywhere-docs#37]
Hi 

According to the post https://stackoverflow.com/questions/16827901/how-do-you-remove-the-root-ca-certificate-that-fiddler-installs the fiddler certificate can be removed . In Fiddler everywhere I do not see this option. When I try the certmgr.msc I see that I cannot find the fiddler certificate. How do I delete the fiddler certificate ?

**Comment by NickIliev** [comment]
@hiddenscroll so far the certificate can be removed only "manually" from the OS settings.

**Comment by hiddenscroll** [comment]
@NickIliev Can you explain a little more ? I dont see the certificate in the OS settings.

**Comment by NickIliev** [comment]
@hiddenscroll sorry for the delay in my answer! Please use [the FIddler Everywhere forums ](https://community.getfiddler.com/support/discussions/12000000385)so that you won't have to wait for your solution so much time.

With the latest version of Fiddler Everywhere, we are now providing UI buttons to export, reset (remove and add), or completely remove the root Fiddler certificate. These options are available under  **_Settings > HTTPS > Advanced_**
